# These are supported funding model platforms

github: TRaSH-
custom: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=P95QYT5662VLN%22", "https://trash-guides.info/#buy-me-a-coffee"
open_collective: trash-guides
