site_name: TRaSH Guides
site_description: Guides mainly for Sonarr/Radarr/Bazarr and everything related to it.
site_author: TRaSH
site_url: https://trash-guides.info/

repo_url: https://github.com/TRaSH-/Guides
repo_name: TRaSH-/Guides

copyright: Copyright &copy; 2020 TRaSH

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/paypal
      link: https://trash-guides.info/#buy-me-a-coffee
    - icon: fontawesome/brands/bitcoin
      link: https://trash-guides.info/#buy-me-a-coffee
    - icon: fontawesome/brands/discord
      link: https://trash-guides.info/discord
    - icon: fontawesome/brands/github-square
      link: https://github.com/TRaSH-/Guides

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - lightgallery

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false
  - awesome-pages
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "[["
      j2_variable_end_string: "]]"
  - redirects:
      redirect_maps:
        discord.md: https://discord.gg/Vau8dZ3
          '/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md': '/Radarr/V3/Radarr-collection-of-custom-formats.md'
          '/Radarr/V3/Radarr-Quality-Settings-File-Size.md': '/Radarr/V3/Radarr-quality-settings-file-size.md'

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
  language: en
  palette:
    primary: indigo
    accent: indigo
    scheme: slate
  font:
    text: "Roboto"
    code: "Fira Code"
  favicon: img/favicon.png
  logo: img/logo.png
