name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.x

      - run: pip install -r requrements.txt

      - run: |
          cp README.md docs/index.md
          cp -r images/ docs

      - run: mkdocs gh-deploy --force
